### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by firminunderscore** [andronedev/megaweb-bot#1]
Afin de simplifier les choses, je te conseille de mettre un package.json (on le fait avec `npm init` ) cela sera plus simple pour installer les dépendances

**Comment by firminunderscore** [comment]
Sinon bon projet !

**Comment by andronedev** [comment]
Salut !

Merci du conseille, je vais faire ca ;)
au passage je compte mettre a jour le bot pour passer a la v12 de discord.js ainsi que de l'améliorer ^^
Encore merci <3
n'hésite pas a mettre un star ^^
